##############################################################################
# HDX DATA FRESHNESS:
#
#  Database:
#   - PostgreSQL
#
#  Program:
#   - HDX Data Freshness: for collecting freshness statistics about HDX.
#
##############################################################################

version: "3.1"

services:
  #
  # Database
  #
  db:
    image: unocha/alpine-postgres:201703-PR116
    restart: always
    environment:
      - PGSQL_USER=${DB_USER}
      - PGSQL_PASS=${DB_PASS}
      - PGSQL_DB=${DB_NAME}
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - "$DB_VOL_BASE_PATH/freshness-db:/var/lib/pgsql"
      - "./docker/db-opt:/opt/db"
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"
  #
  # REST api
  #
  rest:
    image: mcarans/alpine-haskell-postgrest
    restart: always
    depends_on:
      - "db"
    ports:
      - "3000:3000"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
    command: ["sh", "/root/runpostgrest.sh"]
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"

  #
  # Program
  #
  app:
    image: mcarans/hdx-data-freshness
    depends_on:
      - "db"
    hostname: hdx-data-freshness
    volumes:
      - "/:/srv"
    environment:
      - DB_URL=${DB_URL}
    command: ["python3", "-m", "freshness"]
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

