##############################################################################
# HDX DATA FRESHNESS:
#
#  Database:
#   - PostgreSQL
#
#  REST api:
#   - PostgREST
#
#  Data Freshness
#   - HDX Data Freshness: collects freshness statistics about HDX
#
#  Data Freshness Emailer
#   - HDX Data Freshness Emailer: emails when datasets overdue/delinquent
#
##############################################################################

version: "3.1"

services:
  #
  # Database
  #
  db:
    image: unocha/alpine-postgres:201703-PR116
    restart: always
    environment:
      - PGSQL_USER=${DB_USER}
      - PGSQL_PASS=${DB_PASS}
      - PGSQL_DB=${DB_NAME}
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - "$DB_VOL_BASE_PATH/freshness-db:/var/lib/pgsql"
      - "./docker/db-opt:/opt/db"
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"
  #
  # REST api
  #
  rest:
    image: mcarans/alpine-haskell-postgrest
    restart: always
    depends_on:
      - "db"
    ports:
      - "3000:3000"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
    command: ["sh", "/root/runpostgrest.sh"]
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"

  #
  # Data Freshness
  #
  fresh:
    image: mcarans/hdx-data-freshness
    depends_on:
      - "db"
    hostname: hdx-data-freshness
    volumes:
      - "/:/srv"
    environment:
      - HDX_KEY=${HDX_KEY}
      - PREPREFIX=${PREPREFIX}
      - DB_URL=${DB_URL}
    command: ["python3", "-m", "hdx.freshness"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  #
  # Data Freshness Emailer
  #
  email:
    image: mcarans/hdx-data-freshness-emailer
    depends_on:
      - "db"
    hostname: hdx-data-freshness-emailer
    volumes:
      - "/:/srv"
    environment:
      - HDX_KEY=${HDX_KEY}
      - PREPREFIX=${PREPREFIX}
      - DB_URL=${DB_URL}
      - EMAIL_SERVER=${EMAIL_SERVER}
      - 'GSHEET_AUTH=${GSHEET_AUTH}'
    command: ["python3", "-m", "hdx.freshness.emailer"]
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"

