##############################################################################
# HDX DATA FRESHNESS:
#
#  Database:
#   - PostgreSQL
#
#  REST api:
#   - PostgREST
#
#  Data Freshness
#   - HDX Data Freshness: collects freshness statistics about HDX
#
#  Data Freshness Emailer
#   - HDX Data Freshness Emailer: emails when datasets overdue/delinquent
#
##############################################################################

version: "3.1"

services:
  #
  # Database
  #
  db:
    image: unocha/postgis:9.6
    restart: always
    environment:
      - PGSQL_USER=${DB_USER}
      - PGSQL_PASS=${DB_PASS}
      - PGSQL_DB=${DB_NAME}
    volumes:
      - "$BASEDIR/db:/var/lib/pgsql"
      - "$BASEDIR/backup:/backup"
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"
  #
  # REST api
  #
  #rest:
  #  image: mcarans/alpine-haskell-postgrest
  #  restart: always
  #  depends_on:
  #    - "db"
  #  ports:
  #    - "3000:3000"
  #  environment:
  #    - DB_URL=${DB_URL}
  #    - DB_USER=${DB_USER}
  #  command: ["sh", "/root/runpostgrest.sh"]
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-size: "100k"
  #      max-file: "1"

  #
  # Data Freshness
  #
  fresh:
    image: mcarans/hdx-data-freshness
    depends_on:
      - "db"
    hostname: hdx-data-freshness
    environment:
      - HDX_KEY=${HDX_KEY}
      - PREPREFIX=${PREPREFIX}
      - DB_URL=${DB_URL}
    command: ["python3", "-m", "hdx.freshness.app"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  #
  # Data Freshness Emailer
  #
  email:
    image: mcarans/hdx-data-freshness-emailer
    depends_on:
      - "db"
    hostname: hdx-data-freshness-emailer
    environment:
      - HDX_KEY=${HDX_KEY}
      - PREPREFIX=${PREPREFIX}
      - DB_URL=${DB_URL}
      - EMAIL_SERVER=${EMAIL_SERVER}
      - 'GSHEET_AUTH=${GSHEET_AUTH}'
    command: ["python3", "-m", "hdx.freshness.emailer.app"]
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"

